### PR TITLE
Update Russian language | Draft | Version 3.3.2

### PR DESCRIPTION
**Pull request by DrHesperus**

### CODE REVIEW

**Comment by Tslat** [comment]
I'd probably submit this in the next 24h, as 3.3 is on its way.

You'll be able to continue after 3.3's release, which will also include any changes made in 3.3

**Comment by DrHesperus** [comment]
Alright

**Comment by Tslat** [comment]
Remove the stamp with name and date.

It gets removed by my merging program anyway, so it'll never make it in.
Plus I don't want to encourage people to only being helping the mod out as a means to put their name in it.

**Comment by Tslat** [comment]
This is still a draft yeah?

Make sure to click "Ready for review" when you're done

**Comment by DrHesperus** [comment]
Alright, but I was know

**Comment by Tslat** [comment]
Don't edit the english lang file

**Comment by DrHesperus** [comment]
I am sorry, but how to cancel there changes?

**Comment by masterbobli** [comment]
> I am sorry, but how to cancel these changes?

Just copy & paste the older version

**Comment by Ursun1** [comment]
imo formatting is not needed, just mark it as ready if you finished translating

**Comment by Tslat** [comment]
So we now have numerous issues with this.
There's very good reasons we don't batch hundreds of changes into one PR. You should be doing it on a regular basis and allowing me to merge.

1. No formatting codes. The Lang file is for localisation only, not formatting. This will break stuff.
2. You now have several conflicts with other changes that have been made to the base branch, which you haven't yet joined with yours
3. Several of your edits, and basically all of your bestiary entries have broken formatting (show character indicators rather than actual letters.) This usually means you didn't use UTF-8 as the encoding for the text file
4. There's now so many changes in this that it would take me so long to go through them all to find issues that I'm really just not going to bother.

I can guarantee that I will never merge this PR.
If you want me to merge in your localisations, save your work, then start a new PR and submit things bit by bit, and PUSH them to me on a regular basis. Batching these things over literal weeks makes these impossible to work with

**Comment by DrHesperus** [comment]
Good bye

**Comment by DrHesperus** [comment]
You’ve done a mean thing on your part

**Pull request closed without merging**
