### PR TITLE
german translation, WIP

### PR DESCRIPTION
**Pull request by Psychotrickser**

### CODE REVIEW

**Comment by Tslat** [comment]
I don't think ger_ger is an actual language code in MC

**Comment by Psychotrickser** [comment]
uhhh language code? I'm new to this

**Comment by masterbobli** [comment]
> uhhh language code? I'm new to this

Check out this page: https://minecraft.gamepedia.com/Language

**Comment by Psychotrickser** [comment]
Should I close this pull request and rename 'ger_ger' to 'de_de' and create a new pull request?

**Comment by Tslat** [comment]
yeah close this PR and make the necessary changes

**Comment by masterbobli** [comment]
> Should I close this pull request and rename 'ger_ger' to 'de_de' and create a new pull request?

You can just rename the file

**Comment by Tslat** [comment]
Dont' forget the folder where the bestiary files are

**Pull request merged**
