### PR TITLE
Update of zh_cn (2810-3000 lines, message part)

### PR DESCRIPTION
**Pull request by SagvinYg**

### CODE REVIEW

**Comment by Angrydog001** [comment]
Well, why delete that line of string? (Secondly asking)

**Comment by masterbobli** [comment]
Test

**Comment by SagvinYg** [comment]
Well, I indeed shouldn't have ignored these comments. I'll note them from now on.
So I will reply these all now: 
1. “凋零” is exactly a typo, which is my fault.
2. In my opinion, nether should be translated into "下界", while hell should be "地狱". 
3. As for shots, I have fixed them.

Then, need I submit these updates again? Part by part or as a whole?

**Comment by Angrydog001** [comment]
In vanilla, nether should be translated into "下界", and simplified-traditional Chinese conversion (MediaWiki:Conversiontable/zh-hant, MediaWiki:Conversiontable/zh-hans) on Chinese wiki is not allow that "地狱" should be appeared in simplified Chinese. Otherwise if Minecraft's translation proofreader in simplified Chinese (i.e. Powup333, A20001017, Sjjklh) change it to "地狱". 

Anyway, doing translation part by part which is definitely convenient for reviewers to proofread and review. I am also afraid that I denied the translation which were wholly written by you.

**Pull request closed without merging**
