### PR TITLE
Add russian guides, update ru_ru.lang

### PR DESCRIPTION
**Pull request by bigenergy**

### CODE REVIEW

**Comment by Tslat** [comment]
Edits with signatures and credit lines will **not** be accepted.
This isn't a graffiti playground, it's a community effort

**Comment by bigenergy** [comment]
What?

**Comment by barbaratimson** [comment]
Credits can be deleted, but "#" is for other translators. There are 5k lines of names. And sorting them is a good idea.  Why didn`t you liked that?

**Comment by Tslat** [comment]
The program that gets used to merge the files on each update will discard them anyway.

**Comment by barbaratimson** [comment]
I think that`s not a big problem. I don`t want to translate lang file anymore, this is incomplete version. But i 
can translate new guides and bestiary.

**Comment by bigenergy** [comment]
ok i cleaned

**Comment by bigenergy** [comment]
Okay, I close the PR.

**Pull request closed without merging**
