### PR TITLE
修正翻译内容和条目

### PR DESCRIPTION
**Pull request by masterbobli**

### CODE REVIEW

**Comment by Angrydog001** [comment]
Well, why delete that line of string?

**Comment by masterbobli** [comment]
It was a duplicate of the former line and don’t exist in the English version

**Comment by Angrydog001** [comment]
Catch that, this is a fault which is syncing error per Scimiguy. I was just assuring vandalish behavior you haven't made.

**Comment by Angrydog001** [comment]
it could be merged :)

**Pull request merged**
